# fly.toml app configuration file generated for discordbotapi on 2023-12-27T17:22:42+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "discordbotapi"
primary_region = "cdg"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
